apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: us.gcr.io/ticketing-dev-372404/auth
    context: auth
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: us.gcr.io/ticketing-dev-372404/client
    context: client
    sync:
      manual:
      - src: '**/*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  #local:
  #  push: false
  googleCloudBuild:
    projectId: ticketing-dev-372404
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl:
    {}